#!/bin/bash
echo
echo "================================="
echo "EmonPi update started"
echo "================================="

sudo service emonhub stop
sudo service emonPiLCD stop

echo "Start ATmega328 serial upload using avrdude with emonPi_latest.hex"

# emonPi ATmega328 update
vrdude -v -c arduino -p ATMEGA328P -P /dev/ttyO2 -b 115200  -U flash:w:/home/debian/emonpi/Atmega328/emonPi_RFM69CW_RF12Demo_DiscreteSampling/emonPi_RFM69CW_RF12Demo_DiscreteSampling.cpp.hex

sudo service emonhub start
sudo service emonPiLCD start

# RFM12Pi with RFM12B update
# avrdude -v -c arduino -p ATMEGA328P -P /dev/ttyAMA0 -b 38400 -U flash:w:/home/pi/RFM2Pi/firmware/RFM69CW_RF_Demo_ATmega328/RFM12_Demo_ATmega328.cpp.hex

# RFM69Pi with RFM69CW Update
# avrdude -v -c arduino -p ATMEGA328P -P /dev/ttyAMA0 -b 38400 -U flash:w:/home/pi/RFM2Pi/firmware/RFM69CW_RF_Demo_ATmega328/RFM69CW_RF12_Demo_ATmega328.cpp.hex



