#!/bin/bash

echo
echo "================================="
echo "Emonhub update started"
echo 

date

echo

cd /home/debian/emonhub
git config --global http.sslverify false
git checkout beaglebone
git pull origin --tags
git checkout RELEASE
git pull origin RELEASE
pip install -r requirements.txt

sudo service emonhub restart

sudo service emonPiLCD restart

echo
echo "Emonhub update finished"
echo "================================="
echo
