#!/bin/bash

echo
echo "================================="
echo "Emonhub update started"
echo 

date

echo

#cd /var/www/emoncms
#git pull origin low-write

#cd /var/www/emoncms/Modules/nodes
#git pull origin master

#cd /var/www/emoncms/Modules/app
#git pull origin master

#cd /var/www/emoncms/Modules/config
#git pull origin master

#cd /var/www/emoncms/Modules/wifi
#git pull origin master

cd /home/debian/emonhub
git config --global http.sslverify false
git pull origin RELEASE

sudo service emonhub restart
#sudo service emoncms-nodes-service restart
#sudo service feedwriter restart

sudo service emonPiLCD restart

echo
echo "Emonhub update finished"
echo "================================="
echo
