#!/bin/bash

echo "update"
sudo apt-get update -y
sudo apt-get upgrade -y

echo "deleting unused software"
sudo apt-get purge -y wolfram-engine minecraft-pi sonic-pi scratch
sudo apt-get autoremove -y
sudo apt-get clean

echo "Set hostname to emonpi"
sudo sed -i 's/beaglebone/RMC/g' /etc/hosts
sudo sed -i 's/beaglebone/RMC/g' /etc/hostname

echo "install LCD"
sudo /home/debian/emonpi/lcd/install
echo "install wifi dongle"
chmod +x /home/debian/emonpi/install_wifi_autoreset.sh
sudo /home/debian/emonpi/install_wifi_autoreset.sh

echo "move /etc/resolv.conf to RW data partition to allow updating of DNS nameservers"
# create sim link of resolv.conf and resolv.conf.dhclient-new in RW /data to /etc
cp /etc/resolv.conf /home/debian/data/
systemctl disable bonescript.service              
systemctl disable bonescript.socket
systemctl disable bonescript-autorun.service
systemctl disable cloud9.service                  
systemctl disable gateone.service                 
systemctl disable bonescript.service              
systemctl disable bonescript-autorun.service      
systemctl disable avahi-daemon.service            
systemctl disable gdm.service     # this disables the Gnome desktop which is maybe irrelevant here, but saves a ton of memory

# copy modified dhclient-script
sudo cp /home/debian/emonpi/dhclient-script /sbin/dhclient-script

