#!/bin/bash

#if [ ! -f /tmp/emonpiupdate ]; then
#    exit
#fi

LOCK=/tmp/updatelock
if [ -f $LOCK ]; then
  echo Job is already running\!
  exit 6
fi
touch $LOCK

#rpi-rw

cat /dev/null >  /var/log/emonpiupdate.log 

cd /home/debian/emonpi
git config --global http.sslverify false
git checkout beaglebone
#update tags
git pull origin --tags
git checkout RELEASE
#The RELEASE Tag is updated in pull --tags
git pull origin RELEASE

/home/debian/emonpi/emonpiupdate
/home/debian/emonpi/emoncmsupdate

sudo rm /tmp/emonpiupdate

#rpi-ro

rm $LOCK
